// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metrics.proto

package metrics_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContentType int32

const (
	ContentType_Zero        ContentType = 0
	ContentType_MetricsType ContentType = 1007
)

var ContentType_name = map[int32]string{
	0:    "Zero",
	1007: "MetricsType",
}

var ContentType_value = map[string]int32{
	"Zero":        0,
	"MetricsType": 1007,
}

func (x ContentType) String() string {
	return proto.EnumName(ContentType_name, int32(x))
}

func (ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{0}
}

type MetricsMessage struct {
	SourceId             string                                     `protobuf:"bytes,2,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	Timestamp            *timestamp.Timestamp                       `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tags                 map[string]string                          `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IntValues            map[string]int64                           `protobuf:"bytes,5,rep,name=intValues,proto3" json:"intValues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	FloatValues          map[string]float64                         `protobuf:"bytes,6,rep,name=floatValues,proto3" json:"floatValues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Meters               map[string]*MetricsMessage_Meter           `protobuf:"bytes,7,rep,name=meters,proto3" json:"meters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Histograms           map[string]*MetricsMessage_Histogram       `protobuf:"bytes,8,rep,name=histograms,proto3" json:"histograms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IntervalCounters     map[string]*MetricsMessage_IntervalCounter `protobuf:"bytes,9,rep,name=intervalCounters,proto3" json:"intervalCounters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *MetricsMessage) Reset()         { *m = MetricsMessage{} }
func (m *MetricsMessage) String() string { return proto.CompactTextString(m) }
func (*MetricsMessage) ProtoMessage()    {}
func (*MetricsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{0}
}

func (m *MetricsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsMessage.Unmarshal(m, b)
}
func (m *MetricsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsMessage.Marshal(b, m, deterministic)
}
func (m *MetricsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsMessage.Merge(m, src)
}
func (m *MetricsMessage) XXX_Size() int {
	return xxx_messageInfo_MetricsMessage.Size(m)
}
func (m *MetricsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsMessage proto.InternalMessageInfo

func (m *MetricsMessage) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *MetricsMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *MetricsMessage) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *MetricsMessage) GetIntValues() map[string]int64 {
	if m != nil {
		return m.IntValues
	}
	return nil
}

func (m *MetricsMessage) GetFloatValues() map[string]float64 {
	if m != nil {
		return m.FloatValues
	}
	return nil
}

func (m *MetricsMessage) GetMeters() map[string]*MetricsMessage_Meter {
	if m != nil {
		return m.Meters
	}
	return nil
}

func (m *MetricsMessage) GetHistograms() map[string]*MetricsMessage_Histogram {
	if m != nil {
		return m.Histograms
	}
	return nil
}

func (m *MetricsMessage) GetIntervalCounters() map[string]*MetricsMessage_IntervalCounter {
	if m != nil {
		return m.IntervalCounters
	}
	return nil
}

type MetricsMessage_Meter struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	M1Rate               float64  `protobuf:"fixed64,2,opt,name=m1Rate,proto3" json:"m1Rate,omitempty"`
	M5Rate               float64  `protobuf:"fixed64,3,opt,name=m5Rate,proto3" json:"m5Rate,omitempty"`
	M15Rate              float64  `protobuf:"fixed64,4,opt,name=m15Rate,proto3" json:"m15Rate,omitempty"`
	MeanRate             float64  `protobuf:"fixed64,5,opt,name=meanRate,proto3" json:"meanRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsMessage_Meter) Reset()         { *m = MetricsMessage_Meter{} }
func (m *MetricsMessage_Meter) String() string { return proto.CompactTextString(m) }
func (*MetricsMessage_Meter) ProtoMessage()    {}
func (*MetricsMessage_Meter) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{0, 6}
}

func (m *MetricsMessage_Meter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsMessage_Meter.Unmarshal(m, b)
}
func (m *MetricsMessage_Meter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsMessage_Meter.Marshal(b, m, deterministic)
}
func (m *MetricsMessage_Meter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsMessage_Meter.Merge(m, src)
}
func (m *MetricsMessage_Meter) XXX_Size() int {
	return xxx_messageInfo_MetricsMessage_Meter.Size(m)
}
func (m *MetricsMessage_Meter) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsMessage_Meter.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsMessage_Meter proto.InternalMessageInfo

func (m *MetricsMessage_Meter) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MetricsMessage_Meter) GetM1Rate() float64 {
	if m != nil {
		return m.M1Rate
	}
	return 0
}

func (m *MetricsMessage_Meter) GetM5Rate() float64 {
	if m != nil {
		return m.M5Rate
	}
	return 0
}

func (m *MetricsMessage_Meter) GetM15Rate() float64 {
	if m != nil {
		return m.M15Rate
	}
	return 0
}

func (m *MetricsMessage_Meter) GetMeanRate() float64 {
	if m != nil {
		return m.MeanRate
	}
	return 0
}

type MetricsMessage_Histogram struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Max                  int64    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Mean                 float64  `protobuf:"fixed64,3,opt,name=mean,proto3" json:"mean,omitempty"`
	Min                  int64    `protobuf:"varint,4,opt,name=min,proto3" json:"min,omitempty"`
	StdDev               float64  `protobuf:"fixed64,5,opt,name=stdDev,proto3" json:"stdDev,omitempty"`
	Variance             float64  `protobuf:"fixed64,6,opt,name=variance,proto3" json:"variance,omitempty"`
	P50                  float64  `protobuf:"fixed64,7,opt,name=p50,proto3" json:"p50,omitempty"`
	P75                  float64  `protobuf:"fixed64,8,opt,name=p75,proto3" json:"p75,omitempty"`
	P95                  float64  `protobuf:"fixed64,9,opt,name=p95,proto3" json:"p95,omitempty"`
	P99                  float64  `protobuf:"fixed64,10,opt,name=p99,proto3" json:"p99,omitempty"`
	P999                 float64  `protobuf:"fixed64,11,opt,name=p999,proto3" json:"p999,omitempty"`
	P9999                float64  `protobuf:"fixed64,12,opt,name=p9999,proto3" json:"p9999,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsMessage_Histogram) Reset()         { *m = MetricsMessage_Histogram{} }
func (m *MetricsMessage_Histogram) String() string { return proto.CompactTextString(m) }
func (*MetricsMessage_Histogram) ProtoMessage()    {}
func (*MetricsMessage_Histogram) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{0, 7}
}

func (m *MetricsMessage_Histogram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsMessage_Histogram.Unmarshal(m, b)
}
func (m *MetricsMessage_Histogram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsMessage_Histogram.Marshal(b, m, deterministic)
}
func (m *MetricsMessage_Histogram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsMessage_Histogram.Merge(m, src)
}
func (m *MetricsMessage_Histogram) XXX_Size() int {
	return xxx_messageInfo_MetricsMessage_Histogram.Size(m)
}
func (m *MetricsMessage_Histogram) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsMessage_Histogram.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsMessage_Histogram proto.InternalMessageInfo

func (m *MetricsMessage_Histogram) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetMean() float64 {
	if m != nil {
		return m.Mean
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetStdDev() float64 {
	if m != nil {
		return m.StdDev
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetVariance() float64 {
	if m != nil {
		return m.Variance
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetP50() float64 {
	if m != nil {
		return m.P50
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetP75() float64 {
	if m != nil {
		return m.P75
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetP95() float64 {
	if m != nil {
		return m.P95
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetP99() float64 {
	if m != nil {
		return m.P99
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetP999() float64 {
	if m != nil {
		return m.P999
	}
	return 0
}

func (m *MetricsMessage_Histogram) GetP9999() float64 {
	if m != nil {
		return m.P9999
	}
	return 0
}

type MetricsMessage_IntervalCounter struct {
	IntervalLength       uint64                           `protobuf:"varint,1,opt,name=intervalLength,proto3" json:"intervalLength,omitempty"`
	Buckets              []*MetricsMessage_IntervalBucket `protobuf:"bytes,2,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *MetricsMessage_IntervalCounter) Reset()         { *m = MetricsMessage_IntervalCounter{} }
func (m *MetricsMessage_IntervalCounter) String() string { return proto.CompactTextString(m) }
func (*MetricsMessage_IntervalCounter) ProtoMessage()    {}
func (*MetricsMessage_IntervalCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{0, 8}
}

func (m *MetricsMessage_IntervalCounter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsMessage_IntervalCounter.Unmarshal(m, b)
}
func (m *MetricsMessage_IntervalCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsMessage_IntervalCounter.Marshal(b, m, deterministic)
}
func (m *MetricsMessage_IntervalCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsMessage_IntervalCounter.Merge(m, src)
}
func (m *MetricsMessage_IntervalCounter) XXX_Size() int {
	return xxx_messageInfo_MetricsMessage_IntervalCounter.Size(m)
}
func (m *MetricsMessage_IntervalCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsMessage_IntervalCounter.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsMessage_IntervalCounter proto.InternalMessageInfo

func (m *MetricsMessage_IntervalCounter) GetIntervalLength() uint64 {
	if m != nil {
		return m.IntervalLength
	}
	return 0
}

func (m *MetricsMessage_IntervalCounter) GetBuckets() []*MetricsMessage_IntervalBucket {
	if m != nil {
		return m.Buckets
	}
	return nil
}

type MetricsMessage_IntervalBucket struct {
	IntervalStartUTC     int64             `protobuf:"varint,1,opt,name=intervalStartUTC,proto3" json:"intervalStartUTC,omitempty"`
	Values               map[string]uint64 `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MetricsMessage_IntervalBucket) Reset()         { *m = MetricsMessage_IntervalBucket{} }
func (m *MetricsMessage_IntervalBucket) String() string { return proto.CompactTextString(m) }
func (*MetricsMessage_IntervalBucket) ProtoMessage()    {}
func (*MetricsMessage_IntervalBucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_6039342a2ba47b72, []int{0, 9}
}

func (m *MetricsMessage_IntervalBucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsMessage_IntervalBucket.Unmarshal(m, b)
}
func (m *MetricsMessage_IntervalBucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsMessage_IntervalBucket.Marshal(b, m, deterministic)
}
func (m *MetricsMessage_IntervalBucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsMessage_IntervalBucket.Merge(m, src)
}
func (m *MetricsMessage_IntervalBucket) XXX_Size() int {
	return xxx_messageInfo_MetricsMessage_IntervalBucket.Size(m)
}
func (m *MetricsMessage_IntervalBucket) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsMessage_IntervalBucket.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsMessage_IntervalBucket proto.InternalMessageInfo

func (m *MetricsMessage_IntervalBucket) GetIntervalStartUTC() int64 {
	if m != nil {
		return m.IntervalStartUTC
	}
	return 0
}

func (m *MetricsMessage_IntervalBucket) GetValues() map[string]uint64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("metrics.pb.ContentType", ContentType_name, ContentType_value)
	proto.RegisterType((*MetricsMessage)(nil), "metrics.pb.MetricsMessage")
	proto.RegisterMapType((map[string]float64)(nil), "metrics.pb.MetricsMessage.FloatValuesEntry")
	proto.RegisterMapType((map[string]*MetricsMessage_Histogram)(nil), "metrics.pb.MetricsMessage.HistogramsEntry")
	proto.RegisterMapType((map[string]int64)(nil), "metrics.pb.MetricsMessage.IntValuesEntry")
	proto.RegisterMapType((map[string]*MetricsMessage_IntervalCounter)(nil), "metrics.pb.MetricsMessage.IntervalCountersEntry")
	proto.RegisterMapType((map[string]*MetricsMessage_Meter)(nil), "metrics.pb.MetricsMessage.MetersEntry")
	proto.RegisterMapType((map[string]string)(nil), "metrics.pb.MetricsMessage.TagsEntry")
	proto.RegisterType((*MetricsMessage_Meter)(nil), "metrics.pb.MetricsMessage.Meter")
	proto.RegisterType((*MetricsMessage_Histogram)(nil), "metrics.pb.MetricsMessage.Histogram")
	proto.RegisterType((*MetricsMessage_IntervalCounter)(nil), "metrics.pb.MetricsMessage.IntervalCounter")
	proto.RegisterType((*MetricsMessage_IntervalBucket)(nil), "metrics.pb.MetricsMessage.IntervalBucket")
	proto.RegisterMapType((map[string]uint64)(nil), "metrics.pb.MetricsMessage.IntervalBucket.ValuesEntry")
}

func init() {
	proto.RegisterFile("metrics.proto", fileDescriptor_6039342a2ba47b72)
}

var fileDescriptor_6039342a2ba47b72 = []byte{
	// 697 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x7e, 0xdd, 0x38, 0x49, 0x33, 0x7e, 0xdb, 0x46, 0x2b, 0x40, 0x96, 0x2f, 0x54, 0xa8, 0xaa,
	0x68, 0x90, 0xdc, 0x0f, 0x14, 0x5a, 0x57, 0xa8, 0x42, 0x84, 0xaf, 0x22, 0x72, 0x09, 0x81, 0x03,
	0x70, 0xd9, 0xa4, 0x5b, 0xd7, 0x6a, 0x6c, 0x47, 0xf6, 0x26, 0xa2, 0x17, 0x2e, 0xfc, 0x37, 0xfe,
	0x05, 0xbf, 0x81, 0x9f, 0x00, 0xbb, 0xb3, 0xb6, 0xb3, 0x49, 0x43, 0x12, 0x4e, 0xd9, 0xf9, 0x78,
	0x9e, 0x67, 0x3c, 0xb3, 0x3b, 0x81, 0x8d, 0x90, 0xf1, 0x24, 0xe8, 0xa7, 0xee, 0x30, 0x89, 0x79,
	0x4c, 0xa0, 0x30, 0x7b, 0xce, 0x7d, 0x3f, 0x8e, 0xfd, 0x01, 0xdb, 0xc7, 0x48, 0x6f, 0x74, 0xb9,
	0xcf, 0x83, 0x90, 0xa5, 0x9c, 0x86, 0x43, 0x95, 0xfc, 0xe0, 0xe7, 0x06, 0x6c, 0xb6, 0x55, 0x7e,
	0x9b, 0xa5, 0x29, 0xf5, 0x19, 0x71, 0x60, 0x3d, 0x8d, 0x47, 0x49, 0x9f, 0x9d, 0x5f, 0xd8, 0x6b,
	0xdb, 0xc6, 0xc3, 0x5a, 0xa7, 0xb0, 0xc9, 0x09, 0xd4, 0x0a, 0x06, 0xbb, 0x24, 0x82, 0xd6, 0x91,
	0xe3, 0x2a, 0x0d, 0x37, 0xd7, 0x70, 0xbb, 0x79, 0x46, 0x67, 0x92, 0x2c, 0x90, 0x26, 0xa7, 0x7e,
	0x6a, 0x9b, 0xdb, 0x25, 0x01, 0xda, 0x71, 0x27, 0x45, 0xba, 0xd3, 0xfa, 0x6e, 0x57, 0xa4, 0xbd,
	0x8c, 0x78, 0x72, 0xd3, 0x41, 0x04, 0x79, 0x0d, 0xb5, 0x20, 0xe2, 0x1f, 0xe9, 0x60, 0xc4, 0x52,
	0xbb, 0x8c, 0xf0, 0xbd, 0x05, 0xf0, 0xf3, 0x3c, 0x57, 0x71, 0x4c, 0xb0, 0xa4, 0x0d, 0xd6, 0xe5,
	0x20, 0xa6, 0x39, 0x55, 0x05, 0xa9, 0x1e, 0x2d, 0xa0, 0x7a, 0x35, 0xc9, 0x56, 0x64, 0x3a, 0x9e,
	0x9c, 0x41, 0x45, 0x40, 0x59, 0x92, 0xda, 0x55, 0x64, 0xda, 0x5d, 0xc0, 0xd4, 0xc6, 0x44, 0x45,
	0x92, 0xa1, 0xc8, 0x5b, 0x80, 0xab, 0x20, 0xe5, 0xb1, 0x9f, 0xd0, 0x30, 0xb5, 0xd7, 0x91, 0xa3,
	0xb1, 0x80, 0xe3, 0x4d, 0x91, 0xac, 0x78, 0x34, 0x34, 0xf9, 0x02, 0x75, 0xf1, 0x9d, 0x2c, 0x19,
	0xd3, 0x41, 0x2b, 0x1e, 0x45, 0x58, 0x55, 0x0d, 0x19, 0x0f, 0x16, 0xb7, 0x6a, 0x0a, 0xa2, 0x78,
	0x6f, 0x31, 0x39, 0xc7, 0x50, 0x2b, 0x86, 0x42, 0xea, 0x50, 0xba, 0x66, 0x37, 0xb6, 0x81, 0x37,
	0x43, 0x1e, 0xc9, 0x1d, 0x28, 0x8f, 0x65, 0x4b, 0xb2, 0xdb, 0xa2, 0x8c, 0xd3, 0xb5, 0x13, 0xc3,
	0x79, 0x0a, 0x9b, 0xd3, 0xe3, 0x58, 0x86, 0x2e, 0xe9, 0xe8, 0x33, 0xa8, 0xcf, 0x4e, 0x60, 0x19,
	0xde, 0xd0, 0xf1, 0x9f, 0xc1, 0xd2, 0xfa, 0x3e, 0x07, 0xfa, 0x44, 0x87, 0x5a, 0x47, 0xdb, 0xcb,
	0x06, 0xa8, 0x93, 0xf7, 0x61, 0x6b, 0x66, 0x20, 0x73, 0x04, 0x4e, 0xa7, 0x05, 0x76, 0x56, 0x99,
	0xae, 0x2e, 0x12, 0xc3, 0xdd, 0xb9, 0x33, 0x9a, 0x23, 0xf5, 0x6c, 0x5a, 0xaa, 0xb1, 0xfa, 0xd8,
	0x75, 0xc1, 0xef, 0x06, 0x94, 0xf1, 0x53, 0x65, 0x5b, 0xfb, 0x32, 0x8e, 0x1a, 0x62, 0x2c, 0x68,
	0x90, 0x7b, 0xe2, 0xce, 0x1f, 0x76, 0x28, 0xcf, 0xbb, 0x9d, 0x59, 0xe8, 0x6f, 0xa2, 0xbf, 0x94,
	0xf9, 0xd1, 0x22, 0x36, 0x54, 0xc3, 0x43, 0x15, 0x30, 0x31, 0x90, 0x9b, 0x72, 0xcb, 0x84, 0x8c,
	0x46, 0x18, 0x2a, 0x63, 0xa8, 0xb0, 0x9d, 0xdf, 0x06, 0xd4, 0x8a, 0x7e, 0xfc, 0xa5, 0x12, 0xd1,
	0x81, 0x90, 0x7e, 0xcd, 0x2e, 0x8d, 0x3c, 0x12, 0x02, 0xa6, 0x64, 0xc8, 0x2a, 0xc0, 0x33, 0x66,
	0x05, 0x11, 0x6a, 0xcb, 0xac, 0x20, 0x92, 0x95, 0xa6, 0xfc, 0xe2, 0x05, 0x1b, 0x67, 0xaa, 0x99,
	0x25, 0xeb, 0x19, 0xd3, 0x24, 0xa0, 0x51, 0x9f, 0x89, 0xcd, 0x80, 0xf5, 0xe4, 0xb6, 0x64, 0x19,
	0x36, 0x0f, 0xc4, 0x33, 0x97, 0x6e, 0x79, 0x44, 0xcf, 0x71, 0x53, 0x3c, 0x5a, 0xe5, 0x39, 0x6e,
	0xa2, 0xc7, 0x6b, 0x8a, 0x47, 0xa7, 0x3c, 0x5e, 0xe6, 0xf1, 0x6c, 0xc8, 0x3d, 0x9e, 0xac, 0x50,
	0xfc, 0x78, 0xb6, 0xa5, 0x2a, 0x94, 0x67, 0xf9, 0x75, 0xf2, 0xd7, 0xb3, 0xff, 0x57, 0xd7, 0x17,
	0x0d, 0xe7, 0x1b, 0x6c, 0xcd, 0x4c, 0x89, 0xec, 0xc2, 0x66, 0xfe, 0x30, 0xdf, 0xb1, 0xc8, 0xe7,
	0x57, 0xd8, 0x0f, 0xb3, 0x33, 0xe3, 0x25, 0x2d, 0xa8, 0xf6, 0x46, 0xfd, 0x6b, 0xc6, 0x53, 0xd1,
	0x9c, 0x15, 0x96, 0x25, 0x62, 0x9f, 0x23, 0xa2, 0x93, 0x23, 0x9d, 0x1f, 0x06, 0xbe, 0x5c, 0x2d,
	0x46, 0x1a, 0x93, 0x15, 0xf3, 0x9e, 0xd3, 0x84, 0x7f, 0xe8, 0xb6, 0xb2, 0x89, 0xdc, 0xf2, 0x8b,
	0x4d, 0x5b, 0x19, 0xab, 0x25, 0x5b, 0xc2, 0x12, 0x9a, 0x2b, 0x97, 0xe0, 0xea, 0xeb, 0x36, 0x23,
	0x71, 0x3c, 0xb0, 0xfe, 0x61, 0x07, 0x98, 0xda, 0x85, 0x6e, 0xec, 0x81, 0xd5, 0x8a, 0x85, 0x42,
	0xc4, 0xbb, 0x37, 0x43, 0x46, 0xd6, 0xc1, 0xfc, 0xc4, 0x92, 0xb8, 0xfe, 0x9f, 0x20, 0xb1, 0xb2,
	0x42, 0x64, 0xa0, 0xfe, 0xab, 0xda, 0xab, 0xe0, 0x1f, 0xd8, 0xe3, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xea, 0xb6, 0x71, 0xf4, 0x4f, 0x07, 0x00, 0x00,
}
